### PR TITLE
Update ReviewJSONDB.js

### PR DESCRIPTION
**Pull request by vitaly-t**
Easier way to use `ColumnSet` ;)

### CODE REVIEW

**Comment by vitaly-t** [comment]
n.m. cast may be better sometimes ;)

**Comment by mnm1992** [comment]
Cast doesn't work for the update case. So I prefer not to use it

**Comment by mnm1992** [comment]
But thanks for trying to cleanup the code. This is my first attempt to learn node. So there will be a lot of suboptimal code in there.

**Comment by vitaly-t** [comment]
What I suggested to replace ealier - was to explicitely format those columns as `:json`, which should be on, but sometimes `cast` is also required,...

**Comment by mnm1992** [comment]
In this case format also doesn't work. SInce then you get the error trying to insert text in a jsoin column. In the update case.

**Comment by vitaly-t** [comment]
What should always work correctly - use both `cast: 'json'` and `mod: ':json'`. Then you will get the data properly formatted, and then additionally properly cast.

**Pull request closed without merging**
